apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
data:
  env.profile: dev3
  env.profile.bulk: dev3,mongoprojectiondbhost,bulk
  env.profile.realtime: dev3,mongoprojectiondbhost,realtime

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-flux
  namespace: default
data:
  # Configuration values can be set as key-value properties
  git.url: git@github.com:peterfosseus/gitops-tutorial
