apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    project: kafka-manager
    version: 1.3.3.16
  name: kafka-manager
  namespace: monitoring
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: kafka-manager
    spec:
      containers:
        - image: zookeeper:latest
          imagePullPolicy: Always
          name: zookeeper
          ports:
            - containerPort: 2181
              name: zookeeper
              protocol: TCP
        - env:
            - name: ZK_HOSTS
              value: localhost:2181
          image: registry.zailab.com/kafka-manager:1.3.3.16
          name: kafka-manager
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: zailab.registry
      restartPolicy: Always
