apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: kafka-manager
    version: 1.3.3.17
  name: kafka-manager
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: kafka-manager
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:latest
          ports:
            - containerPort: 2181
              name: zookeeper
        - name: kafka-manager
          image: registry.zailab.com/kafka-manager:1.3.3.17
          env:
            - name: ZK_HOSTS
              value: localhost:2181
          ports:
            - containerPort: 9000
              name: http
          resources:
            requests:
              memory: 1536Mi
              cpu: 200m
            limits:
              memory: 1920Mi
              cpu: 1500m
      imagePullSecrets:
        - name: zailab.registry

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30013
      protocol: TCP
  selector:
    project: kafka-manager
